# Generated by Django 3.2.3 on 2021-05-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'permissions': (('create_subdivisions', 'Create subdivisions'),)},
        ),
    ]
